spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/0722?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: guodai
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/mappers/*Mapper.xml
